/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonTrigModule: typeof import('./src/components/gui-module-components/ButtonTrigModule.vue')['default']
    DisplayMessageModule: typeof import('./src/components/gui-module-components/DisplayMessageModule.vue')['default']
    MessageTrigModule: typeof import('./src/components/gui-module-components/MessageTrigModule.vue')['default']
    MidiCCToSignal: typeof import('./src/components/gui-module-components/MidiCCToSignal.vue')['default']
    MidiInputModule: typeof import('./src/components/gui-module-components/MidiInputModule.vue')['default']
    MidiNoteMessageModule: typeof import('./src/components/gui-module-components/MidiNoteMessageModule.vue')['default']
    MidiNoteToTrig: typeof import('./src/components/gui-module-components/MidiNoteToTrig.vue')['default']
    MidiNoteToTrigModule: typeof import('./src/components/gui-module-components/MidiNoteToTrigModule.vue')['default']
    PatchCable: typeof import('./src/components/PatchCable.vue')['default']
    PatchConnection: typeof import('./src/components/PatchConnection.vue')['default']
    PatchContextMenu: typeof import('./src/components/PatchContextMenu.vue')['default']
    PatchModule: typeof import('./src/components/PatchModule.vue')['default']
    PatchModuleInput: typeof import('./src/components/PatchModuleInput.vue')['default']
    PatchModuleOptionsInput: typeof import('./src/components/PatchModuleOptionsInput.vue')['default']
    PatchModuleOutput: typeof import('./src/components/PatchModuleOutput.vue')['default']
    PatchNotesModule: typeof import('./src/components/gui-module-components/PatchNotesModule.vue')['default']
    PatchWindow: typeof import('./src/components/PatchWindow.vue')['default']
    SliderModule: typeof import('./src/components/gui-module-components/SliderModule.vue')['default']
  }
}
