/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioModule: typeof import('./src/components/AudioModule.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PatchCable: typeof import('./src/components/PatchCable.vue')['default']
    PatchConnection: typeof import('./src/components/PatchConnection.vue')['default']
    PatchContextMenu: typeof import('./src/components/PatchContextMenu.vue')['default']
    PatchGraph: typeof import('./src/components/PatchGraph.vue')['default']
    PatchModule: typeof import('./src/components/PatchModule.vue')['default']
    PatchModuleInput: typeof import('./src/components/PatchModuleInput.vue')['default']
    PatchModuleOutput: typeof import('./src/components/PatchModuleOutput.vue')['default']
    PatchWindow: typeof import('./src/components/PatchWindow.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
